### ISSUE TITLE
请问现在结果是否有提升？如何用多卡进行试验？

### ISSUE THREAD

**Issue by wuhua5027** [Spico197/DE-PPN#2]

**Comment by Spico197** [comment]
嗨，您好。现在结果暂时没有提升，还在找问题。不需要使用多卡进行实验，单卡足矣。如果要使用多卡跑的话需要参照Doc2EDAG原始repo添加一个多卡执行脚本，大概长这个样子：

```bash
#! /bin/bash

NUM_GPUS=$1
shift

python -m torch.distributed.launch --nproc_per_node ${NUM_GPUS} run_main.py $*
```

然后再新建一个`.sh`执行脚本进行输入参数的控制。

**Comment by Spico197** [comment]
嗨，多卡的训练脚本已经更新在仓库中，可以查看 `run_multi.sh` 和 `train_multi.sh` 脚本

**Comment by wuhua5027** [comment]
> 

真诚感谢您的回复以及您最近的更新。我在之前做Doc2EDAG实验时，用了6卡150epoch。为了对比，在复现DE－PPN时同样用了6卡150epoch，我注意到您在运行时写入了日志deppn_multi.log，但我想像训练Doc2EDAG那样，能看到具体的每个epoch运行时间及总的预估时间，请问应该在何处改写？同时请问您是如何预估单卡运行时间的？或者您是等全部运行完毕之后统计了运行时间？

**Comment by Spico197** [comment]
嗨，按照本repo readme中的方法，结果会输出到`deppn_multi.log`文件中，之后可以使用`tail -f deppn_multi.log`实时查看程序运行状态。本repo中在训练时是有用`tqdm`的，所以在运行一轮之后可以大致看到预估的剩余时间。不过最靠谱的还是整个实验运行完再根据日志计算运行时间。

不知道是否解答了您的问题，如果有后续问题，欢迎继续交流。

**Comment by wuhua5027** [comment]
![image](https://user-images.githubusercontent.com/45557238/147051540-5013d711-aa69-4ec3-abc4-cb27aad94d5a.png)
但我只显示了这个，并没有显示预估剩余时间，是否是我产生了错误~

**Comment by wuhua5027** [comment]
![image](https://user-images.githubusercontent.com/45557238/147051984-bf5e1721-e546-430c-b8a7-6bec425049a8.png)
同时，我修改了DEE文件中的DEE_task，train_batch_size改为了256（同样也是为了和Doc2EDAG同步），但看起来似乎并没有修改成功

**Comment by Spico197** [comment]
请问您在运行程序时是否严格按照这个格式进行输入（末尾要有`2>&1`）？ 能否提供完整的日志？
`nohup bash run_multi.sh >deppn_multi.log 2>&1 &`

我这里是可以看到时间的：
![image](https://user-images.githubusercontent.com/22840952/147052505-75a64d6b-15de-483b-b41e-fed1c18b5eb8.png)

另外如果是多卡的话，要改`run_multi.sh`中的`train_batch_size`，改代码是没用的，参数会覆盖。

**Comment by wuhua5027** [comment]
![image](https://user-images.githubusercontent.com/45557238/147053583-e9432f41-0828-4b77-a3c0-712bce170487.png)
![image](https://user-images.githubusercontent.com/45557238/147053664-e71f6a9d-eae0-49d8-b407-c56d42d2efd8.png)
您好，我又去检查了一下，刚才的运行语句没有输入错误，且run_multi.sh中的train_batch_size也已经更改。为了放心，我又重新运行了一下，依然没有显示具体的预估时间

**Comment by Spico197** [comment]
很奇怪，不确定是程序卡住了还是显示问题。请直接在命令行中输入`bash run_multi.sh`，检查有没有输出下面的内容

![image](https://user-images.githubusercontent.com/22840952/147054845-e7b0f527-4ebb-4160-a27c-384918437fad.png)

**Comment by wuhua5027** [comment]
> bash run_multi.sh

![image](https://user-images.githubusercontent.com/45557238/147056642-08860680-b2c3-440e-af4b-e492b5ac8686.png)
您好，这是输入bash run_multi.sh的运行结果，在此处出现卡顿。最后为Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

**Comment by Spico197** [comment]
使用默认参数试试看，train_batch_size=16, 卡数改为4

**Comment by wuhua5027** [comment]
![image](https://user-images.githubusercontent.com/45557238/147067761-2427b295-9d5c-4fdf-a728-36906bd9c52b.png)
改好啦，依然是这样子的~

**Comment by Spico197** [comment]
很奇怪。。我刚刚在本地试了一下，运行时没有问题。请问您那边单卡可以正常训练吗？

**Comment by wuhua5027** [comment]
> 很奇怪。。我刚刚在本地试了一下，运行时没有问题。请问您那边单卡可以正常训练吗？

![image](https://user-images.githubusercontent.com/45557238/147072316-5aefa724-767b-4dc2-9cf5-10cfa6b2c4ce.png)
您好呀，单卡可以的，之前单卡也没有问题

**Comment by Spico197** [comment]
抱歉，这个确实是我的知识盲区了，我会保留当前issue的开放状态。如果后面有小伙伴遇到同样问题的话欢迎讨论。
我在TitanXp和V100上测试了代码，CUDA版本分别为10.2和10.1，torch版本1.5.1，目前程序运行无问题。

同学可以在 `base_task.py` 的 `BasePytorchTask` 构造函数中打一些log，看看程序是到哪一步卡住的，现在来看应该是136行之前就卡住了。可以再检查下master address/port以及尝试升级torch、CUDA版本。

另外，我目前的repo可能关注的同学比较少。同学也可以试着在原始repo里提issue问问看看大家有没有遇到过相关问题。

**Comment by xxllp** [comment]
大佬 你有没有遇到 预测的role type 中有一些评估指标都是0的情况  但是这些role 是有数据的

**Comment by Spico197** [comment]
> 大佬 你有没有遇到 预测的role type 中有一些评估指标都是0的情况 但是这些role 是有数据的

与本issue问题无关，建议新开issue讨论。
如果是自己的数据集的话，大部分还是数据本身的问题。这个系列的方法都是使用独立的EventTable处理每一个事件，对数据规模的要求很大。
