### ISSUE TITLE
roletype 的指标都是0

### ISSUE THREAD

**Issue by xxllp** [Spico197/DE-PPN#9]
这个问题就是训练了几轮 看评估的指标发现有一半以上的role type F1都是0 ，试了原来的金融文档数据和自己的数据都是一样的

**Comment by xxllp** [comment]
也不知道是否是代码的问题 还是数据的问题 训练10多轮也是一样

**Comment by Spico197** [comment]
鉴于原始repo中[已有讨论](https://github.com/HangYang-NLP/DE-PPN/issues/16)，本issue将被关闭。
